services:
    caddy:
        image: caddy
        restart: unless-stopped
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - .:/www
        ports:
            - '${FORWARD_PHP_PORT}:80'
    php: &laravel
        build:
            context: .
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '.:/www'
        user: 'sail'
        environment:
            - 'PHP_IDE_CONFIG=${PHP_IDE_CONFIG}'
    reverb:
        <<: *laravel
        command: 'php artisan reverb:start'
        ports:
            - '${FORWARD_REVERB_PORT}:8080'
    queue:
        <<: *laravel
        command: 'php artisan queue:work'
        ports:
            - '0:8080'
    redis:
        image: redis:7.2-alpine
        ports:
            - '${FORWARD_REDIS_PORT}:6379'
